// Copyright 2026 Obmondo
// SPDX-License-Identifier: Apache-2.0

package siemctl

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/Obmondo/kubeaid-cli/pkg/config"
	"github.com/Obmondo/kubeaid-cli/pkg/constants"
)

// Quickstart defaults: one demo tenant on a single machine.
const (
	QuickstartClusterName = "kubesoc-quickstart"
	QuickstartTenantCode  = "demo"
	QuickstartTenantName  = "Demo tenant"
	// QuickstartProfileDir holds the single-node values overrides in a
	// KubeAid checkout: values-single-<chart>.yaml per chart.
	QuickstartProfileDir = "hack/kubesoc-quickstart"
)

// QuickstartOptions are the inputs of WriteQuickstartConfig.
type QuickstartOptions struct {
	// Dir is the working directory; the cluster directory is
	// <Dir>/k8s/<QuickstartClusterName>.
	Dir string
	// Domain is the base domain, e.g. <node IP>.nip.io.
	Domain string
	// AgentAddress is the node IP the agents connect to.
	AgentAddress string
	// KeycloakURL is the Keycloak root URL (including /auth).
	KeycloakURL   string
	ClusterIssuer string
	KubeaidURL    string
	ChartRevision string
	ReconcilerTag string
	TenantCode    string
	TenantName    string
	AITriage      bool
}

// WriteQuickstartConfig writes the quickstart's general.yaml (only forkURLs,
// cluster.name and cluster.securityOperations) and returns the cluster
// directory. An existing file is kept, so a re-run keeps its settings.
func WriteQuickstartConfig(opts QuickstartOptions) (string, string, error) {
	clusterDir := filepath.Join(opts.Dir, "k8s", QuickstartClusterName)
	if err := os.MkdirAll(clusterDir, 0o700); err != nil {
		return "", "", err
	}
	path := filepath.Join(clusterDir, "kubeaid-cli.general.yaml")
	if _, err := os.Stat(path); err == nil {
		return clusterDir, path, nil
	}
	if opts.Domain == "" || opts.AgentAddress == "" || opts.KeycloakURL == "" {
		return "", "", errors.New("--domain, --agent-address and --keycloak-url are required")
	}
	code := opts.TenantCode
	if code == "" {
		code = QuickstartTenantCode
	}
	name := opts.TenantName
	if name == "" {
		name = QuickstartTenantName
	}
	kubeaidURL := opts.KubeaidURL
	if kubeaidURL == "" {
		kubeaidURL = "https://github.com/Obmondo/KubeAid"
	}

	f, err := OpenGeneralConfig(path)
	if err != nil {
		return "", "", err
	}
	f.SetString(kubeaidURL, "forkURLs", "kubeaid", "url")
	if opts.ChartRevision != "" {
		f.SetString(opts.ChartRevision, "forkURLs", "kubeaid", "version")
	}
	// The quickstart installs with Helm from local checkouts; the config
	// repository URL is only needed by the parser.
	f.SetString("https://git.example.com/kubesoc/kubeaid-config.git", "forkURLs", "kubeaidConfig", "url")
	f.SetString(QuickstartClusterName, "forkURLs", "kubeaidConfig", "directory")
	f.SetString(QuickstartClusterName, "cluster", "name")

	dryRun := false
	aiDryRun := true
	cfg := &config.SecurityOperationsConfig{
		Enabled:       true,
		ChartRevision: opts.ChartRevision,
		Domain:        opts.Domain,
		Keycloak:      config.SecurityOperationsKeycloakConfig{URL: opts.KeycloakURL},
		AgentHost:     "agents." + opts.Domain,
		AgentAddress:  opts.AgentAddress,
		ClusterIssuer: opts.ClusterIssuer,
		Reconciler: config.SecurityOperationsReconcilerConfig{
			Enabled:  true,
			ImageTag: opts.ReconcilerTag,
			DryRun:   &dryRun,
		},
		AITriage: config.SecurityOperationsAITriageConfig{
			Enabled:       opts.AITriage,
			DryRun:        &aiDryRun,
			DownloadModel: opts.AITriage,
		},
		Tenants: []config.SecurityOperationsTenant{{
			Code: code,
			Name: name,
			// A non-numeric code has no derived ports.
			AgentPorts: &config.SecurityOperationsAgentPorts{Registration: 1515, Events: 1514},
		}},
	}
	if err := f.SetSecurityOperations(cfg); err != nil {
		return "", "", err
	}
	return clusterDir, path, f.Save()
}

// QuickstartScript returns a POSIX sh script that installs the rendered
// releases with Helm instead of Argo CD: the central release first (it
// creates the tenant namespaces), the sealed Secrets, then each tenant
// release. A release's inline valuesObject is written next to the script, and
// the single-node overrides values-single-<chart>.yaml from the KubeAid
// checkout's quickstart directory are added when present.
func QuickstartScript(releases []HelmRelease, order []string, clusterDir, kubeaidDir, valuesDir string) (string, map[string][]byte, error) {
	byName := map[string]HelmRelease{}
	for _, r := range releases {
		byName[r.Name] = r
	}
	files := map[string][]byte{}
	var b strings.Builder
	b.WriteString("#!/bin/sh\n# Generated by `kubeaid-cli siem quickstart`: installs the security operations\n")
	b.WriteString("# stack with Helm, without Argo CD. Re-running it upgrades in place.\nset -eu\n\n")

	central := constants.NamespaceSecurityOperations
	_, _ = fmt.Fprintf(&b, "kubectl get namespace %s >/dev/null 2>&1 || kubectl create namespace %s\n", central, central)
	_, _ = fmt.Fprintf(&b, "kubectl apply -f %s\n\n", shq(filepath.Join(clusterDir, "sealed-secrets", central)))

	installed := map[string]bool{}
	install := func(rel HelmRelease, wait bool) error {
		args := []string{"helm", "upgrade", "--install", rel.Name, shq(rel.ChartPath), "--namespace", rel.Namespace}
		for _, vf := range rel.ValueFiles {
			args = append(args, "-f", shq(vf))
		}
		if len(rel.ValuesObject) > 0 {
			raw, err := yaml.Marshal(rel.ValuesObject)
			if err != nil {
				return err
			}
			name := rel.Name + ".values.yaml"
			files[name] = raw
			args = append(args, "-f", shq(filepath.Join(valuesDir, name)))
		}
		profile := filepath.Join(kubeaidDir, QuickstartProfileDir, "values-single-"+filepath.Base(rel.Chart)+".yaml")
		//nolint:gosec // G703: a path built from the operator's own KubeAid checkout, only stat-ed.
		if _, err := os.Stat(profile); err == nil {
			args = append(args, "-f", shq(profile))
		}
		if wait {
			args = append(args, "--wait", "--timeout", "30m")
		}
		b.WriteString(strings.Join(args, " ") + "\n")
		installed[rel.Name] = true
		return nil
	}

	if rel, ok := byName[constants.ArgoCDAppSecurityOperations]; ok {
		// Without --wait: it creates the tenant namespaces, and the tenant
		// Secrets below go into them before everything is ready.
		if err := install(rel, false); err != nil {
			return "", nil, err
		}
	}
	var tenants []string
	for _, r := range releases {
		if r.Namespace != central {
			tenants = append(tenants, r.Namespace)
		}
	}
	sort.Strings(tenants)
	for _, ns := range tenants {
		_, _ = fmt.Fprintf(&b, "kubectl apply -f %s\n", shq(filepath.Join(clusterDir, "sealed-secrets", ns)))
	}
	for _, name := range order {
		rel, ok := byName[name]
		if !ok || installed[name] {
			continue
		}
		if err := install(rel, true); err != nil {
			return "", nil, err
		}
	}
	b.WriteString("\necho 'kubesoc quickstart installed. Check it with: kubeaid-cli siem status --cluster-dir " +
		strings.ReplaceAll(clusterDir, "'", "") + "'\n")
	return b.String(), files, nil
}

// shq quotes s for POSIX sh.
func shq(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }
