policies:
  - type: commit
    spec:
      header:
        length: 125
        invalidLastCharacters: .
      conventional:
        types:
          - build
          - chore
          - ci
          - docs
          - feat
          - fix
          - perf
          - refactor
          - revert
          - test
        scopes:
          - ".*"
        descriptionLength: 100
