version: 2

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

changelog:
  use: github

  format: "[{{ .Message }}](https://github.com/Obmondo/kubeaid-cli/commit/{{ .Commit }})"

  filters:
    exclude:
      - init

  # Group commits messages by given regex and title.
  groups:
    - title: ðŸ’« Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: ðŸ› Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: ðŸ¥´ Others
      order: 999

archives:
  - formats: [tar.gz]

    # This name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    # Use zip for windows archives.
    format_overrides:
      - goos: windows
        formats: [zip]

builds:
  - main: ./cmd/kubeaid-cli
    binary: kubeaid-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
dist: build/goreleaser

upx:
  - enabled: true
