# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeaid-cli" do
  name "kubeaid-cli"
  desc "KubeAid CLI helps you operate KubeAid managed Kubernetes cluster lifecycle in a
GitOps native way"
  homepage "https://github.com/Obmondo/kubeaid-cli"
  version "0.17.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeaid-cli"

  on_macos do
    on_intel do
      url "https://github.com/Obmondo/kubeaid-cli/releases/download/v#{version}/kubeaid-cli_Darwin_x86_64.tar.gz"
      sha256 "e573cb0e6eab16ed45414a3ffb7d2bd97354e547791e4dd8ebca80d7f958dcfd"
    end
    on_arm do
      url "https://github.com/Obmondo/kubeaid-cli/releases/download/v#{version}/kubeaid-cli_Darwin_arm64.tar.gz"
      sha256 "655f6156387b445b5b314010e04a86137f9364d103c380fcb93c0eab84f9df3a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Obmondo/kubeaid-cli/releases/download/v#{version}/kubeaid-cli_Linux_x86_64.tar.gz"
      sha256 "40bb2964fbd43c392c93401d096ef90e785ecf77c734634477a645fdadcbc9a8"
    end
    on_arm do
      url "https://github.com/Obmondo/kubeaid-cli/releases/download/v#{version}/kubeaid-cli_Linux_arm64.tar.gz"
      sha256 "da4420a3af2816702e919db5e79917690d7c9bb8860f9d6dec37921cae4305b8"
    end
  end

  # No zap stanza required
end
