# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeaid-cli" do
  name "kubeaid-cli"
  desc "KubeAid CLI helps you operate KubeAid managed Kubernetes cluster lifecycle in a
GitOps native way"
  homepage "https://github.com/Obmondo/kubeaid-cli"
  version "0.18.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeaid-cli"

  on_macos do
    on_intel do
      url "https://github.com/Obmondo/kubeaid-cli/releases/download/v#{version}/kubeaid-cli_Darwin_x86_64.tar.gz"
      sha256 "12a2254292537648bb92384ca15425323408f402a32d45f3cf23cd3dab1c2d4f"
    end
    on_arm do
      url "https://github.com/Obmondo/kubeaid-cli/releases/download/v#{version}/kubeaid-cli_Darwin_arm64.tar.gz"
      sha256 "81a8a0f247a4e2a72862df2dc262ee342be59c9402dd2ea00839d10fce592ec0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Obmondo/kubeaid-cli/releases/download/v#{version}/kubeaid-cli_Linux_x86_64.tar.gz"
      sha256 "a20b4511b82ea08e8950ea8b2ed14183ef634a45b57ca4ae31059030ba5f4f40"
    end
    on_arm do
      url "https://github.com/Obmondo/kubeaid-cli/releases/download/v#{version}/kubeaid-cli_Linux_arm64.tar.gz"
      sha256 "4bfb237f8b1355dfb9db4359ff9b955662a78a098b475eccd884dc6156e7d988"
    end
  end

  # No zap stanza required
end
