# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeaid-cli" do
  name "kubeaid-cli"
  desc "KubeAid CLI helps you operate KubeAid managed Kubernetes cluster lifecycle in a
GitOps native way"
  homepage "https://github.com/Obmondo/kubeaid-cli"
  version "0.17.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeaid-cli"

  on_macos do
    on_intel do
      url "https://github.com/Obmondo/kubeaid-cli/releases/download/v#{version}/kubeaid-cli_Darwin_x86_64.tar.gz"
      sha256 "8da83530eaa3deccbe97c6c06a90b2f299297ad8c66e8b68610bc6f738513c12"
    end
    on_arm do
      url "https://github.com/Obmondo/kubeaid-cli/releases/download/v#{version}/kubeaid-cli_Darwin_arm64.tar.gz"
      sha256 "da759feba44d709ab690d4dfad8dc52c582da5b9fd568a061904bf3daa205e26"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Obmondo/kubeaid-cli/releases/download/v#{version}/kubeaid-cli_Linux_x86_64.tar.gz"
      sha256 "090abb178d194a6dac8cff70cdd9a9b85c73100980191827709e7e2918116909"
    end
    on_arm do
      url "https://github.com/Obmondo/kubeaid-cli/releases/download/v#{version}/kubeaid-cli_Linux_arm64.tar.gz"
      sha256 "1a3e46ed97387c9c48404f4217081aed19564f017a3575e14ecebad4af267997"
    end
  end

  # No zap stanza required
end
