# This workflow will trigger for every change happening within pull_request event lifecycle.
on:
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-22.04-htzhel1-ax42-a
    steps:
      - name: Checkout code
        uses: https://gitea.obmondo.com/Obmondo/checkout@v4.2.2

      - name: Setup Go
        uses: https://gitea.obmondo.com/Obmondo/setup-go@v5.5.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Golang CI lint
        uses: https://gitea.obmondo.com/Obmondo/golangci-lint-action@v7.0.1
        with:
          version: v2.5.0
          args: --timeout=5m --config=.golangci.yaml
