// Copyright 2025 Obmondo
// SPDX-License-Identifier: AGPL3

package hetzner

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path"
	"strings"

	"github.com/Obmondo/kubeaid-cli/pkg/config"
)

// WriteKubeletCSRApproverValuesFile renders the per-cluster
// values-kubelet-csr-approver.yaml under kubeaidConfigDir/argocd-apps/.
// The file pins the postfinance kubelet-csr-approver allow-list to:
//
//  1. The vSwitch private-network CIDR (vSwitch.SubnetCIDRBlock).
//  2. One /32 per bare-metal host, derived at render time from the
//     Robot API's main IP for each ServerID.
//
// Kubelet's serving cert SAN list always includes every local interface
// IP — both the private (vSwitch) and the node's Hetzner-assigned
// public IP — so the approver allow-list must cover both or every CSR
// is denied with "One of the SAN IP addresses, X, is not part of the
// allowed IP Prefixes/Subnets". The wrapper chart at
// kubeaid/argocd-helm-charts/kubelet-csr-approver intentionally ships a
// narrow default (just the vSwitch CIDR) so the bootstrap-time helm
// template install in postKubeadm doesn't trust broad Hetzner ranges
// no real operator would; this file is the per-cluster widening to the
// specific public IPs kubeaid-cli has actually provisioned.
//
// Follow-up removal: once CAPH issue
// https://github.com/syself/cluster-api-provider-hetzner/issues/2095
// lands and kubeaid-cli's go.mod bumps to a CAPH version that includes
// the fix, this function + the wrapper chart can be deleted (CAPH's
// native CSR validator is strictly tighter than postfinance's
// IP-prefix allow-list and doesn't need per-cluster wiring).
func (h *Hetzner) WriteKubeletCSRApproverValuesFile(ctx context.Context, kubeaidConfigDir string) error {
	if !config.UsingHetznerBareMetal() {
		return nil
	}

	hetznerConfig := config.ParsedGeneralConfig.Cloud.Hetzner
	if hetznerConfig.BareMetal == nil || hetznerConfig.BareMetal.VSwitch == nil {
		// Pure-HCloud Hetzner setups don't have a vSwitch; nothing to
		// override beyond the chart default. The CSR validator path
		// uses the HCloudMachine inventory, which doesn't have the
		// HBM blind spot.
		return nil
	}

	var hosts []*config.HetznerBareMetalHost
	if config.ControlPlaneInHetznerBareMetal() {
		hosts = append(hosts, hetznerConfig.ControlPlane.BareMetal.BareMetalHosts...)
	}
	for _, nodeGroup := range hetznerConfig.NodeGroups.BareMetal {
		hosts = append(hosts, nodeGroup.BareMetalHosts...)
	}
	if len(hosts) == 0 {
		return nil
	}

	// Sequential Robot API calls — small N (typically 3 CPs + 3-6
	// workers) and Robot's per-account rate limit is unforgiving.
	cidrs := []string{hetznerConfig.BareMetal.VSwitch.SubnetCIDRBlock}
	for _, host := range hosts {
		publicIP, err := h.getHetznerBareMetalServerIP(host.ServerID)
		if err != nil {
			return fmt.Errorf("fetching Robot main IP for server %s: %w", host.ServerID, err)
		}
		cidrs = append(cidrs, publicIP+"/32")
	}

	// providerIpPrefixes parsing in the postfinance approver
	// (internal/cmd/cmd.go) splits on `,` and feeds each entry to
	// netip.ParsePrefix WITHOUT TrimSpace — any whitespace crashes
	// the controller on startup. Keep this single-line, no spaces.
	content := fmt.Sprintf(`kubelet-csr-approver:
  # Generated by kubeaid-cli; do NOT hand-edit. The list is
  # regenerated on every kubeaid-cli setup-cluster run from the
  # Robot API's main IP for each ServerID in general.yaml.
  #
  # Format: single-line comma-separated, NO whitespace (postfinance
  # approver splits on "," and ParsePrefix's each entry — any space
  # crashes the controller).
  providerIpPrefixes: "%s"
  bypassDnsResolution: true
`, strings.Join(cidrs, ","))

	valuesPath := path.Join(kubeaidConfigDir, "argocd-apps", "values-kubelet-csr-approver.yaml")
	if err := os.WriteFile(valuesPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", valuesPath, err)
	}

	slog.InfoContext(ctx, "Wrote kubelet-csr-approver values file",
		slog.String("path", valuesPath),
		slog.Int("hosts", len(hosts)),
	)
	return nil
}
