// Copyright 2026 Obmondo
// SPDX-License-Identifier: AGPL3

// Package schema exposes a machine-readable description of general.yaml
// and secrets.yaml — the same struct tags and doc comments that drive
// `config generate` and docs/config-reference.md — as a self-contained
// JSON document a non-Go consumer (the Obmondo API's add-cluster web
// form) can render a form from without knowing kubeaid-cli's Go types:
// every field record carries its own path, type, tier, required, default,
// enum and appliesWhen.
//
// The spec is generated by tools/generators/cmd from
// pkg/config/general.go and pkg/config/secrets.go (`make run-generators`)
// and embedded into this package; FormSpec decodes it and stamps Version
// at call time. `kubeaid-cli config schema` (cmd/kubeaid-core/root/config)
// is the published artifact — the API invokes a pinned release binary and
// parses its stdout as JSON.
package schema

import (
	_ "embed"
	"encoding/json"
	"fmt"

	"github.com/Obmondo/kubeaid-cli/pkg/globals"
)

//go:embed formspec.json
var formSpecJSON []byte

// Spec is the machine-readable description of general.yaml and
// secrets.yaml the add-cluster web form is rendered from.
type Spec struct {
	// Version is the kubeaid-cli binary version this spec was published
	// from (globals.KubeaidCLIVersion — ldflags-injected at release build
	// time). Empty or "dev" both mean a local/unreleased build.
	Version string `json:"version"`

	Sections []Section `json:"sections"`
}

// Section groups the fields rendered under one top-level general.yaml or
// secrets.yaml key — e.g. "cluster", "cloud", "aws".
type Section struct {
	// Key is the section's own yaml key and its Path prefix in every
	// field it contains — e.g. "cluster".
	Key   string `json:"key"`
	Title string `json:"title"`

	Fields []Field `json:"fields"`
}

// Field describes one leaf field reachable in general.yaml or
// secrets.yaml — a struct field whose Go type is not itself a known
// config struct (so it takes a value directly, rather than containing
// further fields).
type Field struct {
	// Path is the field's key segments from the document root, e.g.
	// ["cloud","hetzner","hcloud","zone"]. Always an array: segment
	// values may contain "." or "/", which would make splitting a
	// dotted-string path back apart ambiguous.
	Path []string `json:"path"`

	// Type is the field's Go type exactly as kubeaid-cli declares it:
	// "string", "bool", "uint32", "[]string", or — for a slice of
	// struct, e.g. "[]HCloudAutoScalableNodeGroup" — the literal
	// element type name. Callers recognize the "[]" + struct-name shape
	// themselves as a repeatable group; kubeaid-cli does not normalize
	// it to a generic "array" kind.
	Type string `json:"type"`

	// Tier is "basic" (shown by default) or "" (advanced, collapsed
	// behind a UI disclosure).
	Tier string `json:"tier"`

	Required bool     `json:"required"`
	Default  string   `json:"default"`
	Enum     []string `json:"enum"`

	// AppliesWhen is nil when the field always applies, or a single
	// {dotted schema path: [allowed values]} entry — e.g.
	// {"cloud.hetzner.mode": ["hcloud","hybrid"]}. Set directly by the
	// field's own `when` struct tag, or inherited from the nearest
	// ancestor field that declared one.
	AppliesWhen map[string][]string `json:"appliesWhen"`

	Doc string `json:"doc"`
}

// FormSpec decodes the embedded form specification and stamps Version
// from globals.KubeaidCLIVersion.
func FormSpec() (*Spec, error) {
	var spec Spec
	if err := json.Unmarshal(formSpecJSON, &spec); err != nil {
		return nil, fmt.Errorf("parsing embedded form spec: %w", err)
	}

	spec.Version = globals.KubeaidCLIVersion

	return &spec, nil
}
