// Copyright 2026 Obmondo
// SPDX-License-Identifier: AGPL3

package keycloak

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"

	"github.com/Nerzal/gocloak/v13"
	"github.com/stretchr/testify/require"
)

// fakeKeycloak is an in-memory mock of just enough of Keycloak's
// admin API for the reconciler unit tests. It is NOT a faithful
// Keycloak — only the endpoints exercised by the reconciler are
// implemented. Each test asserts behavior plus counts of write
// requests, which lets idempotency be verified without real
// dependencies.
//
// Storage is keyed on realm at the top level so tests can exercise
// multiple realms without interference. Within a realm:
//
//   - clients   : keyed on Keycloak's internal id (uuid)
//   - scopes    : keyed on internal id
//   - users     : keyed on internal id
//
// String IDs are generated by a monotonically-increasing counter
// (see nextID); their exact values shouldn't matter to assertions.
type fakeKeycloak struct {
	mu sync.Mutex

	// realms maps realm name → presence sentinel.
	realms map[string]bool

	// clients/scopes/users keyed by realm, then by internal id.
	clients map[string]map[string]*gocloak.Client
	scopes  map[string]map[string]*gocloak.ClientScope
	users   map[string]map[string]*gocloak.User

	// service-account user id keyed by realm + client internal id.
	// Created on demand when GetClientServiceAccount is called for
	// a client with ServiceAccountsEnabled = true.
	serviceAccounts map[string]map[string]string

	// userClientRoles[realm][userID][clientID][] = role names.
	userClientRoles map[string]map[string]map[string][]string

	// idCounter feeds nextID.
	idCounter int

	// writeCount is incremented on POST / PUT / DELETE / etc. —
	// every non-GET. Tests assert it stays flat across repeated
	// reconciliations.
	writeCount int
}

func newFakeKeycloak() *fakeKeycloak {
	return &fakeKeycloak{
		realms:          make(map[string]bool),
		clients:         make(map[string]map[string]*gocloak.Client),
		scopes:          make(map[string]map[string]*gocloak.ClientScope),
		users:           make(map[string]map[string]*gocloak.User),
		serviceAccounts: make(map[string]map[string]string),
		userClientRoles: make(map[string]map[string]map[string][]string),
	}
}

func (f *fakeKeycloak) nextID() string {
	f.idCounter++
	return fmt.Sprintf("id-%d", f.idCounter)
}

// noteWrite must be called inside f.mu by every non-GET handler.
func (f *fakeKeycloak) noteWrite() { f.writeCount++ }

func (f *fakeKeycloak) handler() http.Handler {
	mux := http.NewServeMux()

	// Admin login. gocloak posts form-encoded credentials here;
	// we don't validate them — the test always passes ("admin", "p")
	// so just emit any non-empty access_token.
	mux.HandleFunc("/realms/master/protocol/openid-connect/token", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{
			"access_token":       "fake-admin-token",
			"expires_in":         3600,
			"refresh_expires_in": 1800,
			"refresh_token":      "fake-refresh",
			"token_type":         "Bearer",
			"not-before-policy":  0,
			"session_state":      "fake-session",
			"scope":              "",
		})
	})

	// All admin endpoints route through /admin/realms/...
	mux.HandleFunc("/admin/realms", f.handleRealms)
	mux.HandleFunc("/admin/realms/", f.handleRealmsPrefixed)

	return mux
}

// handleRealms handles `/admin/realms` (no realm name): only POST
// for realm creation.
func (f *fakeKeycloak) handleRealms(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		// gocloak doesn't list realms via this path in the
		// reconciler, so a 200 with an empty list keeps tests
		// happy if it ever does.
		writeJSON(w, http.StatusOK, []any{})
	case http.MethodPost:
		var realm gocloak.RealmRepresentation
		if err := json.NewDecoder(r.Body).Decode(&realm); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		name := derefString(realm.Realm)
		f.mu.Lock()
		f.realms[name] = true
		f.noteWrite()
		f.mu.Unlock()
		w.Header().Set("Location", "/admin/realms/"+name)
		w.WriteHeader(http.StatusCreated)
	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

// handleRealmsPrefixed routes `/admin/realms/{name}/...` to per-realm
// handlers based on the path tail.
func (f *fakeKeycloak) handleRealmsPrefixed(w http.ResponseWriter, r *http.Request) {
	tail := strings.TrimPrefix(r.URL.Path, "/admin/realms/")
	parts := strings.Split(tail, "/")
	// gocloak posts to /admin/realms/ (with trailing slash) for
	// realm creation, leaving parts == [""] — delegate to the
	// no-realm handler.
	if len(parts) == 0 || parts[0] == "" {
		f.handleRealms(w, r)
		return
	}
	realm := parts[0]

	switch {
	case len(parts) == 1:
		// /admin/realms/{name}
		f.handleSingleRealm(w, r, realm)
	case parts[1] == "clients" && len(parts) == 2:
		f.handleClientsList(w, r, realm)
	case parts[1] == "clients" && len(parts) >= 3:
		f.handleClientByID(w, r, realm, parts[2:])
	case parts[1] == "client-scopes" && len(parts) == 2:
		f.handleClientScopesList(w, r, realm)
	case parts[1] == "client-scopes" && len(parts) >= 3:
		f.handleClientScopeByID(w, r, realm, parts[2:])
	case parts[1] == "users" && len(parts) == 2:
		f.handleUsersList(w, r, realm)
	case parts[1] == "users" && len(parts) >= 3:
		f.handleUserByID(w, r, realm, parts[2:])
	default:
		http.NotFound(w, r)
	}
}

func (f *fakeKeycloak) handleSingleRealm(w http.ResponseWriter, r *http.Request, realm string) {
	f.mu.Lock()
	defer f.mu.Unlock()

	if !f.realms[realm] {
		http.Error(w, "realm not found", http.StatusNotFound)
		return
	}
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	writeJSON(w, http.StatusOK, gocloak.RealmRepresentation{
		Realm:   gocloak.StringP(realm),
		Enabled: gocloak.BoolP(true),
	})
}

// --- clients ---

func (f *fakeKeycloak) handleClientsList(w http.ResponseWriter, r *http.Request, realm string) {
	f.mu.Lock()
	defer f.mu.Unlock()

	switch r.Method {
	case http.MethodGet:
		filter := r.URL.Query().Get("clientId")
		var out []*gocloak.Client
		for _, c := range f.clients[realm] {
			if filter != "" && (c.ClientID == nil || *c.ClientID != filter) {
				continue
			}
			out = append(out, c)
		}
		writeJSON(w, http.StatusOK, out)
	case http.MethodPost:
		var c gocloak.Client
		if err := json.NewDecoder(r.Body).Decode(&c); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		id := f.nextID()
		c.ID = gocloak.StringP(id)
		// If client is confidential and no Secret was supplied, mint
		// one so GetClientSecret has something to return.
		if c.PublicClient == nil || !*c.PublicClient {
			if c.Secret == nil || *c.Secret == "" {
				c.Secret = gocloak.StringP("generated-secret-" + id)
			}
		}
		if f.clients[realm] == nil {
			f.clients[realm] = make(map[string]*gocloak.Client)
		}
		f.clients[realm][id] = &c
		f.noteWrite()
		w.Header().Set("Location", "/admin/realms/"+realm+"/clients/"+id)
		w.WriteHeader(http.StatusCreated)
	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

func (f *fakeKeycloak) handleClientByID(w http.ResponseWriter, r *http.Request, realm string, parts []string) {
	clientInternalID := parts[0]

	switch {
	case len(parts) == 2 && parts[1] == "client-secret":
		f.handleClientSecret(w, r, realm, clientInternalID)
	case len(parts) == 2 && parts[1] == "default-client-scopes":
		f.handleClientDefaultScopesList(w, r, realm, clientInternalID)
	case len(parts) == 3 && parts[1] == "default-client-scopes":
		f.handleClientDefaultScope(w, r, realm, clientInternalID, parts[2])
	case len(parts) == 2 && parts[1] == "service-account-user":
		f.handleClientServiceAccount(w, r, realm, clientInternalID)
	case len(parts) == 2 && parts[1] == "roles":
		f.handleClientRolesList(w, r, realm, clientInternalID)
	case len(parts) == 3 && parts[1] == "roles":
		f.handleClientRoleByName(w, r, realm, clientInternalID, parts[2])
	default:
		http.NotFound(w, r)
	}
}

func (f *fakeKeycloak) handleClientSecret(w http.ResponseWriter, r *http.Request, realm, clientInternalID string) {
	f.mu.Lock()
	defer f.mu.Unlock()

	c, ok := f.clients[realm][clientInternalID]
	if !ok {
		http.Error(w, "client not found", http.StatusNotFound)
		return
	}
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	writeJSON(w, http.StatusOK, gocloak.CredentialRepresentation{
		Value: c.Secret,
		Type:  gocloak.StringP("secret"),
	})
}

func (f *fakeKeycloak) handleClientDefaultScopesList(w http.ResponseWriter, r *http.Request, realm, clientInternalID string) {
	f.mu.Lock()
	defer f.mu.Unlock()

	c, ok := f.clients[realm][clientInternalID]
	if !ok {
		http.Error(w, "client not found", http.StatusNotFound)
		return
	}
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	var out []gocloak.ClientScope
	if c.DefaultClientScopes != nil {
		for _, name := range *c.DefaultClientScopes {
			out = append(out, gocloak.ClientScope{Name: gocloak.StringP(name)})
		}
	}
	writeJSON(w, http.StatusOK, out)
}

func (f *fakeKeycloak) handleClientDefaultScope(w http.ResponseWriter, r *http.Request, realm, clientInternalID, scopeID string) {
	f.mu.Lock()
	defer f.mu.Unlock()

	c, ok := f.clients[realm][clientInternalID]
	if !ok {
		http.Error(w, "client not found", http.StatusNotFound)
		return
	}
	scope, ok := f.scopes[realm][scopeID]
	if !ok || scope.Name == nil {
		http.Error(w, "scope not found", http.StatusNotFound)
		return
	}
	if r.Method != http.MethodPut {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// Idempotently add the scope name to the client's defaults.
	current := []string{}
	if c.DefaultClientScopes != nil {
		current = append(current, *c.DefaultClientScopes...)
	}
	for _, existing := range current {
		if existing == *scope.Name {
			f.noteWrite()
			w.WriteHeader(http.StatusNoContent)
			return
		}
	}
	current = append(current, *scope.Name)
	c.DefaultClientScopes = &current
	f.noteWrite()
	w.WriteHeader(http.StatusNoContent)
}

func (f *fakeKeycloak) handleClientServiceAccount(w http.ResponseWriter, r *http.Request, realm, clientInternalID string) {
	f.mu.Lock()
	defer f.mu.Unlock()

	c, ok := f.clients[realm][clientInternalID]
	if !ok {
		http.Error(w, "client not found", http.StatusNotFound)
		return
	}
	if c.ServiceAccountsEnabled == nil || !*c.ServiceAccountsEnabled {
		http.Error(w, "service accounts not enabled", http.StatusBadRequest)
		return
	}
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	if f.serviceAccounts[realm] == nil {
		f.serviceAccounts[realm] = make(map[string]string)
	}
	userID, ok := f.serviceAccounts[realm][clientInternalID]
	if !ok {
		userID = f.nextID()
		username := "service-account-" + derefString(c.ClientID)
		if f.users[realm] == nil {
			f.users[realm] = make(map[string]*gocloak.User)
		}
		f.users[realm][userID] = &gocloak.User{
			ID:       gocloak.StringP(userID),
			Username: gocloak.StringP(username),
		}
		f.serviceAccounts[realm][clientInternalID] = userID
	}
	writeJSON(w, http.StatusOK, gocloak.User{
		ID:       gocloak.StringP(userID),
		Username: f.users[realm][userID].Username,
	})
}

func (f *fakeKeycloak) handleClientRolesList(w http.ResponseWriter, r *http.Request, realm, clientInternalID string) {
	f.mu.Lock()
	defer f.mu.Unlock()

	c, ok := f.clients[realm][clientInternalID]
	if !ok {
		http.Error(w, "client not found", http.StatusNotFound)
		return
	}
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	// Roles are sourced from the client's configured roles via
	// pre-seeded test fixture; if absent, return empty.
	roles, ok := clientRolesFixture[derefString(c.ClientID)]
	if !ok {
		roles = nil
	}
	writeJSON(w, http.StatusOK, roles)
}

func (f *fakeKeycloak) handleClientRoleByName(w http.ResponseWriter, r *http.Request, realm, clientInternalID, roleName string) {
	f.mu.Lock()
	c, ok := f.clients[realm][clientInternalID]
	f.mu.Unlock()
	if !ok {
		http.Error(w, "client not found", http.StatusNotFound)
		return
	}
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	roles, ok := clientRolesFixture[derefString(c.ClientID)]
	if !ok {
		http.Error(w, "no roles", http.StatusNotFound)
		return
	}
	for _, role := range roles {
		if role.Name != nil && *role.Name == roleName {
			writeJSON(w, http.StatusOK, role)
			return
		}
	}
	http.Error(w, "role not found", http.StatusNotFound)
}

// clientRolesFixture pre-seeds roles for known clients so role
// tests don't need to set them up via a mutator API.
var clientRolesFixture = map[string][]*gocloak.Role{
	"realm-management": {
		{
			ID:   gocloak.StringP("role-view-users"),
			Name: gocloak.StringP("view-users"),
		},
		{
			ID:   gocloak.StringP("role-manage-users"),
			Name: gocloak.StringP("manage-users"),
		},
	},
}

// --- client scopes ---

func (f *fakeKeycloak) handleClientScopesList(w http.ResponseWriter, r *http.Request, realm string) {
	f.mu.Lock()
	defer f.mu.Unlock()

	switch r.Method {
	case http.MethodGet:
		var out []*gocloak.ClientScope
		for _, s := range f.scopes[realm] {
			out = append(out, s)
		}
		writeJSON(w, http.StatusOK, out)
	case http.MethodPost:
		var s gocloak.ClientScope
		if err := json.NewDecoder(r.Body).Decode(&s); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		id := f.nextID()
		s.ID = gocloak.StringP(id)
		if f.scopes[realm] == nil {
			f.scopes[realm] = make(map[string]*gocloak.ClientScope)
		}
		f.scopes[realm][id] = &s
		f.noteWrite()
		w.Header().Set("Location", "/admin/realms/"+realm+"/client-scopes/"+id)
		w.WriteHeader(http.StatusCreated)
	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

func (f *fakeKeycloak) handleClientScopeByID(w http.ResponseWriter, r *http.Request, realm string, parts []string) {
	scopeID := parts[0]
	switch {
	case len(parts) == 2 && parts[1] == "protocol-mappers":
		f.handleScopeProtocolMappersList(w, r, realm, scopeID)
	case len(parts) == 3 && parts[1] == "protocol-mappers" && parts[2] == "models":
		// Keycloak's POST endpoint is /protocol-mappers/models
		f.handleScopeProtocolMapperCreate(w, r, realm, scopeID)
	default:
		http.NotFound(w, r)
	}
}

func (f *fakeKeycloak) handleScopeProtocolMappersList(w http.ResponseWriter, r *http.Request, realm, scopeID string) {
	f.mu.Lock()
	defer f.mu.Unlock()

	scope, ok := f.scopes[realm][scopeID]
	if !ok {
		http.Error(w, "scope not found", http.StatusNotFound)
		return
	}
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	out := []*gocloak.ProtocolMappers{}
	if scope.ProtocolMappers != nil {
		for i := range *scope.ProtocolMappers {
			out = append(out, &(*scope.ProtocolMappers)[i])
		}
	}
	writeJSON(w, http.StatusOK, out)
}

func (f *fakeKeycloak) handleScopeProtocolMapperCreate(w http.ResponseWriter, r *http.Request, realm, scopeID string) {
	f.mu.Lock()
	defer f.mu.Unlock()

	scope, ok := f.scopes[realm][scopeID]
	if !ok {
		http.Error(w, "scope not found", http.StatusNotFound)
		return
	}
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	var m gocloak.ProtocolMappers
	if err := json.NewDecoder(r.Body).Decode(&m); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	mappers := []gocloak.ProtocolMappers{}
	if scope.ProtocolMappers != nil {
		mappers = *scope.ProtocolMappers
	}
	m.ID = gocloak.StringP(f.nextID())
	mappers = append(mappers, m)
	scope.ProtocolMappers = &mappers
	f.noteWrite()
	w.WriteHeader(http.StatusCreated)
}

// --- users ---

func (f *fakeKeycloak) handleUsersList(w http.ResponseWriter, r *http.Request, realm string) {
	f.mu.Lock()
	defer f.mu.Unlock()

	switch r.Method {
	case http.MethodGet:
		filter := r.URL.Query().Get("username")
		var out []*gocloak.User
		for _, u := range f.users[realm] {
			if filter != "" && (u.Username == nil || *u.Username != filter) {
				continue
			}
			out = append(out, u)
		}
		writeJSON(w, http.StatusOK, out)
	case http.MethodPost:
		var u gocloak.User
		if err := json.NewDecoder(r.Body).Decode(&u); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		id := f.nextID()
		u.ID = gocloak.StringP(id)
		if f.users[realm] == nil {
			f.users[realm] = make(map[string]*gocloak.User)
		}
		f.users[realm][id] = &u
		f.noteWrite()
		w.Header().Set("Location", "/admin/realms/"+realm+"/users/"+id)
		w.WriteHeader(http.StatusCreated)
	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

func (f *fakeKeycloak) handleUserByID(w http.ResponseWriter, r *http.Request, realm string, parts []string) {
	userID := parts[0]
	switch {
	case len(parts) == 2 && parts[1] == "reset-password":
		f.handleUserResetPassword(w, r, realm, userID)
	case len(parts) >= 3 && parts[1] == "role-mappings" && parts[2] == "clients":
		f.handleUserClientRoles(w, r, realm, userID, parts[3:])
	default:
		http.NotFound(w, r)
	}
}

func (f *fakeKeycloak) handleUserResetPassword(w http.ResponseWriter, r *http.Request, realm, userID string) {
	f.mu.Lock()
	defer f.mu.Unlock()

	if f.users[realm] == nil || f.users[realm][userID] == nil {
		http.Error(w, "user not found", http.StatusNotFound)
		return
	}
	if r.Method != http.MethodPut {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	f.noteWrite()
	w.WriteHeader(http.StatusNoContent)
}

func (f *fakeKeycloak) handleUserClientRoles(w http.ResponseWriter, r *http.Request, realm, userID string, parts []string) {
	if len(parts) == 0 {
		http.NotFound(w, r)
		return
	}
	clientInternalID := parts[0]

	f.mu.Lock()
	defer f.mu.Unlock()

	if f.userClientRoles[realm] == nil {
		f.userClientRoles[realm] = make(map[string]map[string][]string)
	}
	if f.userClientRoles[realm][userID] == nil {
		f.userClientRoles[realm][userID] = make(map[string][]string)
	}

	switch r.Method {
	case http.MethodGet:
		assigned := f.userClientRoles[realm][userID][clientInternalID]
		out := []*gocloak.Role{}
		// Resolve role names to *gocloak.Role from the fixture so
		// the names + IDs round-trip cleanly.
		c, ok := f.clients[realm][clientInternalID]
		if !ok {
			writeJSON(w, http.StatusOK, out)
			return
		}
		fixture := clientRolesFixture[derefString(c.ClientID)]
		for _, name := range assigned {
			for _, role := range fixture {
				if role.Name != nil && *role.Name == name {
					out = append(out, role)
				}
			}
		}
		writeJSON(w, http.StatusOK, out)
	case http.MethodPost:
		var roles []gocloak.Role
		if err := json.NewDecoder(r.Body).Decode(&roles); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		current := f.userClientRoles[realm][userID][clientInternalID]
		for _, role := range roles {
			if role.Name == nil {
				continue
			}
			already := false
			for _, existing := range current {
				if existing == *role.Name {
					already = true
					break
				}
			}
			if !already {
				current = append(current, *role.Name)
			}
		}
		f.userClientRoles[realm][userID][clientInternalID] = current
		f.noteWrite()
		w.WriteHeader(http.StatusNoContent)
	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

// --- helpers ---

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

func derefString(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}

// newTestReconciler spins up a fake Keycloak, logs in as admin,
// and returns the resulting Reconciler plus the fake (so tests can
// inspect / reset state) and the cleanup handle.
func newTestReconciler(t *testing.T) (*Reconciler, *fakeKeycloak) {
	t.Helper()

	fake := newFakeKeycloak()
	srv := httptest.NewServer(fake.handler())
	t.Cleanup(srv.Close)

	r, err := NewReconciler(context.Background(), srv.URL, "admin", "p")
	require.NoError(t, err)
	return r, fake
}
