// Copyright 2025 Obmondo
// SPDX-License-Identifier: AGPL3

package config

type (
	SecretsConfig struct {
		AWS      *AWSCredentials      `yaml:"aws"`
		Azure    *AzureCredentials    `yaml:"azure"`
		Hetzner  *HetznerCredentials  `yaml:"hetzner"`
		Obmondo  *ObmondoCredentials  `yaml:"obmondo"`
		Keycloak *KeycloakCredentials `yaml:"keycloak"`
		NetBird  *NetBirdCredentials  `yaml:"netbird"`
	}

	// KeycloakCredentials carries Keycloak-related secrets — admin
	// credentials and OIDC client secrets the operator either
	// supplies (external mode) or kubeaid-cli auto-generates and
	// persists into secrets.yaml (managed mode, via FillMissingSecrets).
	//
	// All fields are persisted in secrets.yaml so SealedSecret
	// renders are byte-stable across re-runs — the alternative
	// (read-or-generate from the in-cluster Secret) caused the
	// re-encryption noise that produced spurious PRs on every run.
	KeycloakCredentials struct {
		// AdminPassword is templated into the keycloak-admin
		// SealedSecret's KEYCLOAK_PASSWORD key. Required when
		// cluster.keycloak.mode is "managed"; ignored otherwise.
		// FillMissingSecrets generates a value here on first run if
		// the field is empty.
		AdminPassword string `yaml:"adminPassword"`

		// NetBirdBackendClientSecret is the confidential-client
		// secret for the netbird-backend OIDC client. In external
		// mode the operator creates the client in their Keycloak
		// and supplies the resulting secret here. In managed mode
		// FillMissingSecrets generates it, the realm reconciler
		// creates the Keycloak client with this exact value, and
		// the netbird SealedSecret is templated with the same
		// value — single source of truth either way.
		NetBirdBackendClientSecret string `yaml:"netBirdBackendClientSecret"`
	}

	// NetBirdCredentials carries the random secrets NetBird's
	// in-cluster components need at startup. All fields are
	// auto-generated by FillMissingSecrets when blank. Persisted
	// in secrets.yaml for re-run stability — same rationale as
	// KeycloakCredentials.
	NetBirdCredentials struct {
		// DatastoreEncryptionKey is the AES key NetBird Mgmt uses
		// to encrypt its data store. base64(32 random bytes); the
		// chart base64-decodes it back to 32 raw bytes for
		// AES-256.
		DatastoreEncryptionKey string `yaml:"datastoreEncryptionKey"`

		// RelayPassword is the shared secret between NetBird Mgmt
		// and the in-cluster Relay deployment. Alphanumeric so it
		// flows cleanly through Helm values + envFrom.
		RelayPassword string `yaml:"relayPassword"`

		// TurnPassword is the credential the NetBird agents use to
		// authenticate with Coturn (TURN server). Same value is
		// templated into both the netbird Secret (Mgmt-side) and
		// the netbird-turn-credentials Secret (Coturn-side) — the
		// two MUST match or relayed TURN auth fails.
		TurnPassword string `yaml:"turnPassword"`
	}

	ObmondoCredentials struct {
		// TeleportAuthToken is the join token teleport-kube-agent uses to
		// register with the Teleport cluster. Required when
		// obmondo.monitoring is true and obmondo.teleportAgent isn't false.
		TeleportAuthToken string `yaml:"teleportAuthToken"`
	}

	AWSCredentials struct {
		AWSAccessKeyID     string `yaml:"accessKeyID"     validate:"notblank"`
		AWSSecretAccessKey string `yaml:"secretAccessKey" validate:"notblank"`
		AWSSessionToken    string `yaml:"sessionToken"`
	}

	AzureCredentials struct {
		ClientID string `yaml:"clientID" validate:"notblank"`
		//nolint:gosec // This struct intentionally models user-provided Azure credentials.
		ClientSecret string `yaml:"clientSecret" validate:"notblank"`
	}

	HetznerCredentials struct {
		// APIToken is the HCloud Cloud-API token; required for any
		// mode that touches HCloud (hcloud, hybrid). Pure bare-metal
		// clusters don't talk to the HCloud API at all and may leave
		// this empty — the requirement is enforced via cross-mode
		// validation in pkg/config/parser/validate.go, not by the
		// struct-level notblank tag, since "required" here is
		// conditional on cloud.hetzner.mode.
		//
		//nolint:gosec // This struct intentionally models user-provided Hetzner credentials.
		APIToken string                   `yaml:"apiToken"`
		Robot    *HetznerRobotCredentials `yaml:"robot"`
	}

	HetznerRobotCredentials struct {
		User string `yaml:"user" validate:"notblank"`
		//nolint:gosec // This struct intentionally models user-provided Hetzner Robot credentials.
		Password string `yaml:"password" validate:"notblank"`
	}
)
