// Copyright 2026 Obmondo
// SPDX-License-Identifier: AGPL3

package main

import (
	"context"
	"fmt"
	"log/slog"
	"os"

	"github.com/Obmondo/kubeaid-bootstrap-script/cmd/kubeaid-core/root/version"
	"github.com/Obmondo/kubeaid-bootstrap-script/pkg/config"
	"github.com/Obmondo/kubeaid-bootstrap-script/pkg/constants"
	"github.com/Obmondo/kubeaid-bootstrap-script/pkg/containerruntime"
	"github.com/Obmondo/kubeaid-bootstrap-script/pkg/globals"
	"github.com/Obmondo/kubeaid-bootstrap-script/pkg/utils"
)

var (
	sshAuthSock           = os.Getenv(constants.EnvNameSSHAuthSock)
	sshKnownHostsFilePath = utils.ToAbsolutePath(context.Background(), "~/.ssh/known_hosts")
)

type KubeAidCoreContainer struct {
	containerRuntime containerruntime.ContainerRuntime
	imagePullPolicy  containerruntime.ImagePullPolicy

	managementClusterName string
	generalConfig         *config.GeneralConfig
	commandArgs           []string
}

func (k *KubeAidCoreContainer) Run(ctx context.Context) {
	// Ensure that the container image is available, respecting the pull policy.
	imageRef := fmt.Sprintf("ghcr.io/obmondo/kubeaid-core:%s", version.Version)
	k.containerRuntime.PullImage(ctx, imageRef, k.imagePullPolicy)

	// Determine the Docker network inside which it'll run.
	// And, ensure that the Docker network is created.
	networkName := k.getNetworkName()
	if networkName != constants.DockerDefaultNetworkName {
		k.containerRuntime.CreateNetwork(ctx, networkName)
	}

	// Determine required volume bind mounts.
	bindMounts := k.getBindMounts(ctx)

	// Run the KubeAid Core container,
	// proxying command execution to it.
	k.containerRuntime.RunContainer(ctx, containerruntime.RunContainerOptions{
		Name:     "kubeaid-core",
		ImageRef: imageRef,

		Network: networkName,

		Binds: bindMounts,
		Envs: []string{
			fmt.Sprintf("%s=%s", constants.EnvNameSSHAuthSock, sshAuthSock),

			// Go Git doesn't automatically pickup the ~/.ssh/known_hosts file.
			// But rather, expects the SSH_KNOWN_HOSTS environment variable to be set to the path of
			// the SSH known hosts file.
			fmt.Sprintf("%s=%s", constants.EnvNameSSHKnownHosts, sshKnownHostsFilePath),
		},

		Command: k.commandArgs,
	})
}

func (k *KubeAidCoreContainer) getNetworkName() string {
	networkName := constants.DockerDefaultNetworkName
	//
	// When we're not using the Bare Metal provider, KubeAid Core needs to spinup a local management
	// cluster using K3D.
	// But, for it to be able to easily communicate with the management cluster nodes (which are
	// Docker containers themselves), it needs to be in the same Docker network as them.
	if globals.CloudProviderName != constants.CloudProviderBareMetal {
		networkName = fmt.Sprintf("k3d-%s", k.managementClusterName)
	}

	return networkName
}

func (k *KubeAidCoreContainer) getBindMounts(ctx context.Context) map[string]string {
	// Config is already parsed by the original PersistentPreRun.
	configsDirectory := utils.ToAbsolutePath(ctx, globals.ConfigsDirectory)

	binds := map[string]string{
		// Container Runtime socket.
		constants.DockerSocketPath: constants.DockerSocketPath,

		// Directory containing KubeAid CLI configuration files, i.e., general.yaml and secrets.yaml.
		configsDirectory: configsDirectory,

		// Output directory, where artifacts generated by KubeAid CLI will be stored.
		utils.ToAbsolutePath(ctx, "./outputs"): "/outputs",

		// Temp directory, where Git repositories will get cloned.
		constants.TempDirectory: constants.TempDirectory,

		// SSH known hosts file.
		sshKnownHostsFilePath: sshKnownHostsFilePath,
	}

	// SSH auth socket.
	switch len(sshAuthSock) == 0 {
	case true:
		slog.WarnContext(ctx, "SSH_AUTH_SOCK environment variable not set")

	default:
		binds[sshAuthSock] = sshAuthSock
	}

	// SSH private key files.
	for _, privateKeyFilePath := range k.getSSHPrivateKeyFilePaths() {
		privateKeyFilePath = utils.ToAbsolutePath(ctx, privateKeyFilePath)
		binds[privateKeyFilePath] = privateKeyFilePath
	}

	// Obmondo mTLS cert + private key (required when obmondo.monitoring is true).
	// Mount them into the container so validation + downstream template
	// rendering can reach the files at the same absolute path.
	if k.generalConfig.Obmondo != nil && k.generalConfig.Obmondo.Monitoring {
		if k.generalConfig.Obmondo.CertPath != "" {
			p := utils.ToAbsolutePath(ctx, k.generalConfig.Obmondo.CertPath)
			binds[p] = p
		}
		if k.generalConfig.Obmondo.KeyPath != "" {
			p := utils.ToAbsolutePath(ctx, k.generalConfig.Obmondo.KeyPath)
			binds[p] = p
		}
	}

	return binds
}

// Returns the list of SSH private key file paths.
// Those SSH private key files will be mounted to the KubeAid Core container.
func (k *KubeAidCoreContainer) getSSHPrivateKeyFilePaths() []string {
	paths := []string{}

	// Used by ArgoCD to access the KubeAid and KubeAid Config repositories.
	deployKeys := k.generalConfig.Cluster.ArgoCD.DeployKeys
	if deployKeys.Kubeaid != nil {
		paths = append(paths, deployKeys.Kubeaid.PrivateKeyFilePath)
	}
	paths = append(paths, deployKeys.KubeaidConfig.PrivateKeyFilePath)

	// Used to clone the Git repositories.
	if k.generalConfig.Git.SSHKeyPairConfig != nil {
		paths = append(paths, k.generalConfig.Git.PrivateKeyFilePath)
	}

	switch globals.CloudProviderName {
	case constants.CloudProviderAzure:
		azureConfig := k.generalConfig.Cloud.Azure

		// Used to setup Workload Identity.
		paths = append(paths, azureConfig.WorkloadIdentity.OpenIDProviderSSHKeyPair.PrivateKeyFilePath)

	case constants.CloudProviderHetzner:
		hetznerConfig := k.generalConfig.Cloud.Hetzner

		// Used to SSH into the Hetzner Bare Metal / HCloud servers.
		paths = append(paths, hetznerConfig.SSHKeyPair.PrivateKeyFilePath)

	case constants.CloudProviderBareMetal:
		bareMetalConfig := k.generalConfig.Cloud.BareMetal

		// Used to SSH into the Bare Metal servers.

		if bareMetalConfig.SSH.SSHKeyPairConfig != nil {
			paths = append(paths, bareMetalConfig.SSH.PrivateKeyFilePath)
		}

		for _, host := range bareMetalConfig.ControlPlane.Hosts {
			if (host.SSH != nil) && (host.SSH.SSHKeyPairConfig != nil) {
				paths = append(paths, host.SSH.PrivateKeyFilePath)
			}
		}

		for _, nodeGroup := range bareMetalConfig.NodeGroups {
			for _, host := range nodeGroup.Hosts {
				if (host.SSH != nil) && (host.SSH.SSHKeyPairConfig != nil) {
					paths = append(paths, host.SSH.PrivateKeyFilePath)
				}
			}
		}
	}

	return paths
}
