// Copyright 2025 Obmondo
// SPDX-License-Identifier: AGPL3

package main

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"os"
	"os/signal"
	"path"
	"path/filepath"
	"strings"
	"syscall"

	"github.com/containerd/containerd/errdefs"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/image"
	"github.com/docker/docker/api/types/network"
	"github.com/docker/docker/client"
	"github.com/docker/docker/pkg/jsonmessage"
	"github.com/moby/term"
	v1 "github.com/opencontainers/image-spec/specs-go/v1"
	"github.com/spf13/cobra"

	kubeaidCoreRoot "github.com/Obmondo/kubeaid-bootstrap-script/cmd/kubeaid-core/root"
	"github.com/Obmondo/kubeaid-bootstrap-script/cmd/kubeaid-core/root/version"
	"github.com/Obmondo/kubeaid-bootstrap-script/pkg/config"
	"github.com/Obmondo/kubeaid-bootstrap-script/pkg/config/parser"
	"github.com/Obmondo/kubeaid-bootstrap-script/pkg/constants"
	"github.com/Obmondo/kubeaid-bootstrap-script/pkg/globals"
	"github.com/Obmondo/kubeaid-bootstrap-script/pkg/utils/assert"
)

func main() {
	//nolint:reassign
	// By default, parent's PersistentPreRun gets overridden by a child's PersistentPreRun.
	// We want to disable this overriding behaviour and chain all the PersistentPreRuns.
	// REFERENCE : https://github.com/spf13/cobra/pull/2044.
	cobra.EnableTraverseRunHooks = true

	rootCmd := createRootCommand()

	err := rootCmd.Execute()
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
}

// Constructs the root command.
func createRootCommand() *cobra.Command {
	// The interface should be same as that of KubeAid core.
	rootCmd := kubeaidCoreRoot.RootCmd

	rootCmd.Use = "kubeaid-cli"

	// Proxy cluster and devenv subcommands to containerized KubeAid core.
	for _, subCommand := range rootCmd.Commands() {
		subCommandName := subCommand.Name()

		if (subCommandName != "cluster") && (subCommandName != "devenv") {
			continue
		}

		// Unset PersistentPreRun and Run,
		// for this subcommand, and subcommands of this subcommand.
		unsetRunners(subCommand)

		// Proxy command execution to containerized KubeAid Core.
		subCommand.PersistentPreRun = proxyRun
	}

	return rootCmd
}

// Unsets PersistentPreRun and Run,
// for the given command, as well as, its subcommands.
func unsetRunners(command *cobra.Command) {
	command.PersistentPreRun = nil
	command.Run = func(cmd *cobra.Command, args []string) {}

	for _, subCommand := range command.Commands() {
		unsetRunners(subCommand)
	}
}

func proxyRun(command *cobra.Command, args []string) {
	ctx := command.Context()

	// Parse and validate config files.
	configsDirectory := MustAbs(ctx, globals.ConfigsDirectory)
	parser.ParseConfigFiles(ctx, configsDirectory)

	// Determine current working directory.
	workingDirectory, err := os.Getwd()
	assert.AssertErrNil(ctx, err, "Failed determining working directory")

	slog.InfoContext(ctx, "Proxying command execution to KubeAid Core container")

	// Determine management cluster name.
	managementClusterName, err := command.Flags().GetString(constants.FlagNameManagementClusterName)
	assert.AssertErrNil(ctx, err, "Failed getting management-cluster-name flag value")

	dockerCLI, err := client.NewClientWithOpts(
		client.WithHostFromEnv(),
		client.WithAPIVersionNegotiation(),
	)
	assert.AssertErrNil(ctx, err, "Failed creating docker CLI")

	// The KubeAid Core container should run in the same Docker network,
	// where the K3D management cluster is / will be running.
	// Create that Docker network, if it doesn't already exist.

	networkName := fmt.Sprintf("k3d-%s", managementClusterName)

	_, err = dockerCLI.NetworkCreate(ctx, networkName, network.CreateOptions{})
	if !errdefs.IsConflict(err) {
		assert.AssertErrNil(ctx, err,
			"Failed creating Docker network",
			slog.String("name", networkName),
		)
	}

	// Pull the KubeAid Core container image, if it doesn't exist locally.

	containerImageName := fmt.Sprintf("ghcr.io/obmondo/kubeaid-core:v%s", version.Version)

	pullProgressReader, err := dockerCLI.ImagePull(ctx, containerImageName, image.PullOptions{})
	assert.AssertErrNil(ctx, err, "Failed ensuring that KubeAid Core container image exists locally")
	defer pullProgressReader.Close()

	stdoutFD, isTerminal := term.GetFdInfo(os.Stdout)
	_ = jsonmessage.DisplayJSONMessagesStream(pullProgressReader, os.Stdout, stdoutFD, isTerminal, nil)

	// Determine volume bind mounts, for the KubeAid Core container.

	sshKnownHostsFilePath := MustAbs(ctx, "~/.ssh/known_hosts")

	binds := []string{
		// (1) Container Runtime (Docker Engine) socket.
		"/var/run/docker.sock:/var/run/docker.sock",

		// (2) Directory containing KubeAid CLI configuration files, i.e., general.yaml and secrets.yaml.
		fmt.Sprintf("%s:%s", configsDirectory, configsDirectory),

		// (3) Output directory, where artifacts generated by KubeAid CLI will be stored.
		fmt.Sprintf("%s:/outputs",
			path.Join(workingDirectory, "outputs")),

		// (4) Temp directory, where Git repositories will get cloned.
		fmt.Sprintf("%s:%s", constants.TempDirectory, constants.TempDirectory),

		// (5) SSH known hosts file.
		fmt.Sprintf("%s:%s", sshKnownHostsFilePath, sshKnownHostsFilePath),
	}

	// (6) SSH Auth Socket.
	sshAuthSock := os.Getenv(constants.EnvNameSSHAuthSock)
	switch len(sshAuthSock) == 0 {
	case true:
		slog.WarnContext(ctx, "SSH_AUTH_SOCK environment variable not set")

	default:
		binds = append(binds,
			fmt.Sprintf("%s:%s", sshAuthSock, sshAuthSock),
		)
	}

	// (7) SSH private key files.
	for privateKeyFilePath := range getSSHPrivateKeyFilePaths() {
		privateKeyFilePath = MustAbs(ctx, privateKeyFilePath)

		binds = append(binds,
			fmt.Sprintf("%s:%s", privateKeyFilePath, privateKeyFilePath),
		)
	}

	// Spin up the KubeAid Core container,
	// proxying the command execution.

	slog.InfoContext(ctx, "Spinning up KubeAid Core container")

	containerCreateResponse, err := dockerCLI.ContainerCreate(ctx,
		&container.Config{
			Image: containerImageName,

			// In case of the bare-metal provider, the user might need to provide YubiKey pin for SSH
			// authentication against bare-metal servers.
			// So, we need a pseudo-terminal for the container, and keep the standard input accessible
			// from the host.
			Tty:       true,
			OpenStdin: true,

			AttachStdout: true,
			AttachStderr: true,

			Env: []string{
				fmt.Sprintf("%s=%s", constants.EnvNameSSHAuthSock, sshAuthSock),

				// Go Git doesn't automatically pickup the ~/.ssh/known_hosts file.
				// But rather, expects the SSH_KNOWN_HOSTS environment variable to be set to the path of
				// the SSH known hosts file.
				fmt.Sprintf("%s=%s", constants.EnvNameSSHKnownHosts, sshKnownHostsFilePath),
			},

			Cmd: os.Args[1:],
		},
		&container.HostConfig{
			NetworkMode: container.NetworkMode(networkName),
			Binds:       binds,
			AutoRemove:  true,
		},
		&network.NetworkingConfig{},
		&v1.Platform{},
		"kubeaid-core",
	)
	assert.AssertErrNil(ctx, err, "Failed creating KubeAid Core container")

	containerID := containerCreateResponse.ID

	containerAttachResponse, err := dockerCLI.ContainerAttach(ctx, containerID,
		container.AttachOptions{
			Stdin: true,

			Stdout: true,
			Stderr: true,
			Stream: true,
		},
	)
	assert.AssertErrNil(ctx, err, "Failed attaching the KubeAid Core container to the host program")
	defer containerAttachResponse.Close()

	err = dockerCLI.ContainerStart(ctx, containerID, container.StartOptions{})
	assert.AssertErrNil(ctx, err, "Failed starting KubeAid Core container")

	// Stream container logs, to this host program's stdout and stderr.
	go func() {
		_, err := io.Copy(os.Stdout, containerAttachResponse.Reader)
		assert.AssertErrNil(ctx, err, "Failed streaming KubeAid Core container logs")
	}()

	// Wait until the KubeAid Core container exits naturally.
	// Or, if we receive a program termination signal, then we explicitly stop the container, which
	// then gets auto-removed.

	containerStatusChan, containerExecutionErrorChan := dockerCLI.ContainerWait(ctx,
		containerID, container.WaitConditionNotRunning,
	)

	terminationSignalChan := make(chan os.Signal, 1)
	signal.Notify(terminationSignalChan, syscall.SIGINT, syscall.SIGTERM)

	select {
	case err := <-containerExecutionErrorChan:
		assert.AssertErrNil(ctx, err, "KubeAid Core container execution failed")

	case <-containerStatusChan:

	case <-terminationSignalChan:
		err := dockerCLI.ContainerStop(ctx, containerID, container.StopOptions{})
		assert.AssertErrNil(ctx, err, "Failed stopping the KubeAid Core container")
	}
}

// Returns canonical version of the given path.
func MustAbs(ctx context.Context, path string) string {
	// When the path starts with "~/", we need to expand "~" to the user's home directory path.
	// REFER : https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html.
	if strings.HasPrefix(path, "~/") {
		homeDir, err := os.UserHomeDir()
		assert.AssertErrNil(ctx, err, "Failed getting home directory")

		path = homeDir + path[1:]
		return path
	}

	absolutePath, err := filepath.Abs(path)
	assert.AssertErrNil(ctx, err, "Failed canonicalizing given path", slog.String("path", path))

	return absolutePath
}

// Returns the list of SSH private key file paths.
// Those SSH private key files will be mounted to the KubeAid Core container.
func getSSHPrivateKeyFilePaths() map[string]bool {
	paths := map[string]bool{}

	parsedGeneralConfig := config.ParsedGeneralConfig

	// Used to clone the Git repositories.
	if parsedGeneralConfig.Git.SSHPrivateKeyConfig != nil {
		paths[parsedGeneralConfig.Git.PrivateKeyFilePath] = true
	}

	switch globals.CloudProviderName {
	case constants.CloudProviderAzure:
		azureConfig := parsedGeneralConfig.Cloud.Azure

		// Used to setup Workload Identity.
		paths[azureConfig.WorkloadIdentity.OpenIDProviderSSHKeyPair.PrivateKeyFilePath] = true

	case constants.CloudProviderHetzner:
		hetznerConfig := parsedGeneralConfig.Cloud.Hetzner

		if config.UsingHetznerBareMetal() {
			// Used to SSH into the Hetzner Bare Metal servers.
			paths[hetznerConfig.BareMetal.SSHKeyPair.PrivateKeyFilePath] = true
		}

	case constants.CloudProviderBareMetal:
		bareMetalConfig := parsedGeneralConfig.Cloud.BareMetal

		// Used to SSH into the Bare Metal servers.

		if bareMetalConfig.SSH.PrivateKey != nil {
			paths[bareMetalConfig.SSH.PrivateKey.PrivateKeyFilePath] = true
		}

		for _, host := range bareMetalConfig.ControlPlane.Hosts {
			if (host.SSH != nil) && (host.SSH.PrivateKey != nil) {
				paths[host.SSH.PrivateKey.PrivateKeyFilePath] = true
			}
		}

		for _, nodeGroup := range bareMetalConfig.NodeGroups {
			for _, host := range nodeGroup.Hosts {
				if (host.SSH != nil) && (host.SSH.PrivateKey != nil) {
					paths[host.SSH.PrivateKey.PrivateKeyFilePath] = true
				}
			}
		}
	}

	return paths
}
