name: Release

# This Github Action workflow is triggered, when a new tag is pushed.
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  scan_sourcecode:
    name: Scanning sourcecode to find vulberabilities, misconfigurations and exposed secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create outputs directory
        run: mkdir -p /tmp/trivy

      - name: Run Trivy security scan against the sourcecode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          trivy-config: trivy.yaml
          output: security-scan-result.txt
          exit-code: 0
          version: v0.70.0

      - name: Append the security scan result to the job summary
        run: |
          {
            echo "### 🛡️ Sourcecode security scan result :"
            echo ""
            echo '```terraform'
            cat security-scan-result.txt
            echo '```'
          } >> $GITHUB_STEP_SUMMARY

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Cocogito
        uses: cocogitto/cocogitto-action@v4
        with:
          command: get-version

      - name: Generate Changelog
        run: cog changelog --at ${{ github.ref_name }} -t full_hash > GITHUB_CHANGELOG.md

      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ github.ref_name }}

  build_and_publish_kubeaid_cli_binaries:
    name: Build and publish KubeAid CLI binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --parallelism 1 -f .goreleaser-github.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}